#!/data/data/com.termux/files/usr/bin/bash
# Hmei7

clear

blue='\e[0;34'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

###################################################
# CTRL C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "
sleep 1
echo ""
echo -e $green"[#]> Hmei7 sayang fanny "
sleep 1
echo ""
echo -e $white"[#]> Hmei7 in here!!!!! ... "
read enter
exit
}

echo -e $red"
 _   _                _ _____    __                         
 | | | |_ __ ___   ___(_)___  |  / _| __ _ _ __  _ __  _   _ 
 | |_| | '_ ` _ \ / _ \ |  / /  | |_ / _` | '_ \| '_ \| | | |
 |  _  | | | | | |  __/ | / /   |  _| (_| | | | | | | | |_| |
 |_| |_|_| |_| |_|\___|_|/_/    |_|  \__,_|_| |_|_| |_|\__, |
                                                       |___/ 
													   
	by Hmei7, hmei7 sayang fanny												   
"
echo ""
echo -e $green" 01) Chat robot Hmei7"
echo -e $green" 02) Daftar Surat Alquran buat hapalan"
echo -e $green" 03) Zodiak"
echo -e $green" 04) buat hitung gaji fanny sayang"
echo -e $green" 05) buat spam aku"
echo -e $green" 06) Chat robot hmei7 2"
echo -e $white""
read -p "[root@Hmei7:~#]>" hmei7;

if [ $hmei7 = 01 ] || [ $hmei7 = 01 ]
then
clear
echo -e $green" installing robot hmei7..."
sleep 1
apt update && apt upgrade
pkg install python
pip2 install requests
pip2 install urllib
pip2 install sys
curl -O https://raw.githubusercontent.com/ramdanRm19/trash/main/robot.py
echo -e $green" Sukses!"
echo -e $green" cara pakai : python robot.py"
fi

if [ $hmei7 = 02 ] || [ $hmei7 = 02 ]
then
clear
echo -e $green" installing AL QURAN"
pkg install ruby
gem install httparty
curl -O https://raw.githubusercontent.com/ramdanRm19/trash/main/alquran.rb
echo -e $green" Sukses!"
echo -e $green" cara pakai : ruby alquran.rb"
fi

if [ $hmei7 = 03 ] || [ $hmei7 = 03 ]
then
clear
echo -e $green" Installing Zodiak "
sleep 1
apt update && apt upgrade
pkg install python
pip install os
pip install json
pip install requests
curl -O https://raw.githubusercontent.com/ramdanRm19/trash/main/zodiak.py
echo -e $green" done! "
echo -e $green" cara gunakan : python zodiak.py"
fi

if [ $hmei7 = 04 ] || [ $hmei7 = 04 ]
then
clear
echo -e $green" installing gaji"
sleep 1
pkg install ruby
curl -O https://raw.githubusercontent.com/ramdanRm19/trash/main/gaji.rb
echo -e $green"Sukses! "
echo -e $green"cara pakai : ruby gaji.rb"
fi

if [ $hmei7 = 05 ] || [ $hmei7 = 05 ]
then
clear
echo -e $green" instaling auto jailin temen"
sleep 1
pkg install python2
pip2 install requests
pip2 install json
pip2 install os
pip2 install sys
curl -O https://raw.githubusercontent.com/ramdanRm19/trash/main/spamaku.py
echo -e $green"Sukses!"
echo -e $green" cara pakai : python2 spamaku.py"
fi

if [ $hmei7 = 06 ] || [ $hmei7 = 06 ]
then
clear
echo -e $green" install chat bot hmei7 2"
sleep 1
pkg install python
pip install requests
curl -O https://raw.githubusercontent.com/ramdanRm19/trash/main/robothmei7.py
echo -e $green"Sukses!"
echo -e $green" cara pakai : python robothmei7.py"
fi
